# Generated by Django 2.2.1 on 2019-06-27 12:00

from django.db import migrations
import json
from django.contrib.gis.geos import fromstr
from pathlib import Path


DATA_FILENAME = 'data_police_loc.json'
def load_data(apps, schema_editor):
    Agent = apps.get_model('geograph', 'Agent')
    jsonfile = Path(__file__).parents[2] / DATA_FILENAME

    with open(str(jsonfile)) as datafile:
        objects = json.load(datafile)
        for obj in objects['elements']:
            try:
                objType = obj['type']
                if objType == 'node':
                    name = obj.get('id','no-name')
                    longitude = obj.get('lon', 0)
                    latitude = obj.get('lat', 0)
                    location = fromstr(f'POINT({longitude} {latitude})', srid=4326)
                    Agent(name=name, location = location).save()
            except KeyError:
                pass 


class Migration(migrations.Migration):

    dependencies = [
        ('geograph', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_data)
    ]