# Generated by Django 2.2.1 on 2019-06-28 12:49

#SRID=4326;MULTIPOLYGON (((5.46853065414564 50.65637157395672, 5.47986030502297 50.64984143092698, 5.46750068588408 50.65060332772376, 5.465097426607079 50.65408612715706, 5.46853065414564 50.65637157395672)))
#SRID=4326;POINT (5.4437202 51.2316752)

from django.db import migrations
import json
from django.contrib.gis.geos import fromstr
from pathlib import Path


DATA_FILENAME = 'query.json'
def load_data(apps, schema_editor):
    ZI = apps.get_model('geograph', 'ZI')
    jsonfile = Path(__file__).parents[2] / DATA_FILENAME
    with open(str(jsonfile)) as datafile:
        objects = json.load(datafile)
        for obj in objects['features']:
            name = obj.get('id',"lol")
            print(name)
            polygon = obj['geometry']['coordinates']
            for i, poly in enumerate(polygon):
                if poly == '[':
                    poly[i] = ''

            print(polygon)
            location = fromstr(f'MULTIPOLYGON({polygon})', srid=4326)
            ZI(name = name, location=location).save()


class Migration(migrations.Migration):

    dependencies = [
        ('geograph', '0002_auto_20190627_1530'),
    ]

    operations = [
        migrations.RunPython(load_data)
    ]