# Generated by Django 2.2.1 on 2019-05-18 21:09

from django.db import migrations
import json
from django.contrib.gis.geos import fromstr
from pathlib import Path


DATA_FILENAME = 'file.json'
def load_data(apps, schema_editor):
    Agent = apps.get_model('geograph', 'Agent')
    jsonfile = Path(__file__).parents[2] / DATA_FILENAME

    with open(str(jsonfile)) as datafile:
        objects = json.load(datafile)
        for obj in objects['elements']:
            longitude = obj.get('lon', 0)
            latitude = obj.get('lat', 0)
            location = fromstr(f'POINT({longitude} {latitude})', srid=4326)
            Agent(location = location).save() 
            try:
                tags = obj['tags']
                name = tags.get('name','no-name')
                Agent(name=name).save()
            except KeyError:
                pass     


class Migration(migrations.Migration):

    dependencies = [
        ('geograph', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_data)
    ]


